# ###
# basic jekyll config
# ###
title: Brainz Wiki
email: hanna.brainz13@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is supposed to work as a wiki for both me and others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainz13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  brainz13
remote_theme: just-the-docs/just-the-docs
plugins:
# - jekyll-feed
- jekyll-seo-tag


# ###
# just-the-docs configuration
# ###
# For help see https://just-the-docs.github.io/just-the-docs/docs/configuration/

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/Logo-BooksBrain.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "About":
    - "/"
 # "Linkedin":
 #   - "//www.linkedin.com/in/david-halletz/"
  "GitHub":
    - "//github.com/brainz13"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Code formatting
compress_html:
  ignore:
    envs: all
    
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
